### ISSUE TITLE
Saving records with DS.EmbeddedRecordsMixin

### ISSUE THREAD

**Issue by seifsallam** [emberjs/data#1730]
I have a model that has many embedded `programs` and belongs to an embedded `place`. After saving I get this error. While the update request is sent successfully with the embedded data included. 

``` js
TypeError: Cannot read property 'programs' of undefined
    at null.<anonymous> (http://localhost:9000/bower_components/ember-data/ember-data.js:10443:19)
    at http://localhost:9000/bower_components/ember-data/ember-data.js:7169:16
    at http://localhost:9000/bower_components/ember/ember.js:3192:16
    at Object.OrderedSet.forEach (http://localhost:9000/bower_components/ember/ember.js:3035:10)
    at Object.Map.forEach (http://localhost:9000/bower_components/ember/ember.js:3190:10)
    at Function.DS.Model.reopenClass.eachRelationship (http://localhost:9000/bower_components/ember-data/ember-data.js:7168:38)
    at updatePayloadWithEmbedded (http://localhost:9000/bower_components/ember-data/ember-data.js:10425:8)
    at DS.EmbeddedRecordsMixin.Ember.Mixin.create.extractSingle (http://localhost:9000/bower_components/ember-data/ember-data.js:10395:5)
    at superWrapper [as extractSingle] (http://localhost:9000/bower_components/ember/ember.js:1230:16)
    at null.extractSave (http://localhost:9000/bower_components/ember-data/ember-data.js:146:29) ember.js:3285
Assertion failed: 
TypeError {stack: "TypeError: Cannot read property 'programs' of unde…bower_components/ember-data/ember-data.js:146:29)", message: "Cannot read property 'programs' of undefined"}
```

Here is my setup. 

``` js
App.ListingSerializer = App.ApplicationSerializer.extend(
  DS.EmbeddedRecordsMixin, {
  attrs: {
    place: { embedded: 'always' },
    programs: { embedded: 'always' }
  }
});

App.Listing = DS.Model.extend({
  title: DS.attr(),
  body: DS.attr(),
  place: DS.belongsTo('place'),
  programs: DS.hasMany('program')
});

/*
DEBUG: -------------------------------
DEBUG: Ember      : 1.3.1
DEBUG: Ember Data : 1.0.0-beta.6
DEBUG: Handlebars : 1.3.0 
DEBUG: jQuery     : 2.0.3 
DEBUG: ------------------------------- 
*/
```

**Comment by ChrisHonniball** [comment]
I'm seeing this error in beta.17 it's not my response as it happens before the request is sent.
