### ISSUE TITLE
canary - ember-data.js.map Not Found

### ISSUE THREAD

**Issue by mikepmunroe** [emberjs/data#2557]
Upon installing Ember Data Canary, I have started to get the following exception,

GET http://localhost:4200/assets/ember-data.js.map 404 (Not Found)

**Comment by gnapse** [comment]
I'm still getting this error, so what should I do to fix it? It doesn't appear to have any consequences, other than the annoying error message in the browser's console. I'm using the most recent starter kit with Ember 1.9.1, and Ember Data 1.0.0-beta.15-canary (as reported in the console).

**Comment by bmac** [comment]
@gnapse With the starter kit you will need to manually include this file in the same directory as ember data. http://builds.emberjs.com/canary/ember-data.js.map

**Comment by fivetanley** [comment]
We should include this in the starter kit.

**Comment by gnapse** [comment]
Thanks @bmac for the solution. Regarding the inclusion of this in the starter kit @fivetanley, I don't think it should be done, as long as the starter kit continues shipping without ember data, as it does now. It should be noted though when you download ember data, that you also need this file.

BTW, what's this file needed for? As I mentioned above, my project is working perfectly without it. It's just the annoyance of having this error pop out in the console. But I assume there's more to it. What is it?

**Comment by vasilakisfil** [comment]
Hello! I am not sure how relevant it is but when I start my app I get this error:
```bash
version: 0.1.6
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
Path or pattern "ember-data.js.map" did not match any files
Error: Path or pattern "ember-data.js.map" did not match any files
    at Object.multiGlob (/home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at /home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/broccoli-static-compiler/index.js:28:27
    at $$$internal$$tryCatch (/home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/vasilakisfil/Development/rails_tutorial_api/rails_tutorial_ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

If I remove ember-data from packages.json it works but I need that :P

packages.json:
```javascript
{
  "name": "rails-tutorial-ember",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^1.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-merge-trees": "^0.2.1",
    "broccoli-sass": "^0.3.3",
    "broccoli-static-compiler": "^0.2.1",
    "ember-cli": "^0.1.6",
    "ember-cli-6to5": "^0.2.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.6",
    "ember-cli-gravatar": "^1.5.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-pagination": "^0.6.3",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "^1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}
```

Brocfile.js:
```javascript
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.


app.import('bower_components/jquery/dist/jquery.min.js');
app.import('bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js');

module.exports = app.toTree();
```

What other info do you need from me?

**Comment by fivetanley** [comment]
What's in your bower.json?

**Comment by vasilakisfil** [comment]
My bower.json:
```javascript
{
  "name": "rails-tutorial-ember",
  "dependencies": {
    "handlebars": "~1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.12",
    "ember-resolver": "~0.1.10",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "ember-addons.bs_for_ember": "~0.7.0",
    "bootstrap-sass-official": "~3.3.1",
    "JavaScript-MD5": "~1.1.0"
  }
}
```

**Comment by vasilakisfil** [comment]
Hmm seems like it's fixed with 0.1.7! yay!

**Comment by dave8401** [comment]
I'm hitting this issue `Path or pattern "ember-data.js.map" did not match any files` with [beta 15](http://emberjs.com/blog/2015/02/14/ember-data-1-0-beta-15-released.html). Has the sourcemap not been published to bower?

**Comment by bmac** [comment]
@dave8401 I just did a fresh install with `bower install ember-data#1.0.0-beta.15` and I see a `ember-data.js.map` file in my `bower_components/ember-data/` directory. Can you confirm that the version of Ember Data in your `bower_components/ember-data/` is 1.0.0-beta.15?

**Comment by dave8401** [comment]
@bmac thanks, it must have been some issue with bower. I swiped the bower directory, cleaned the cache and did a fresh install -> all good.
