### ISSUE TITLE
Cannot contribute - npm install fails with latest version

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#2652]
npm install -g ember-cli bower && npm install

gives:
```
npm WARN package.json ember-router-generator@0.1.0 No description
npm WARN package.json broccoli-es3-safe-recast@0.0.8 No README data
npm WARN package.json es6-module-transpiler-package-resolver@1.0.1 No repository
 field.
npm WARN package.json defeatureify@0.1.4 No description
npm WARN package.json defeatureify@0.1.4 No repository field.
bower handlebars      extra-resolution Unnecessary resolution: handlebars#>= 2.0
.0 < 3.0.0

npm ERR! ember-data@1.0.0-beta.15-canary dist: `ember build --environment=produc
tion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary dist script.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment=production
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "dist"
npm ERR! cwd F:\Projects\ember-data
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\Projects\ember-data\npm-debug.log
npm ERR! not ok code 0

npm ERR! ember-data@1.0.0-beta.15-canary prepublish: `bower install && npm run-s
cript dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary prepublish script.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && npm run-script dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd F:\Projects\ember-data
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\Projects\ember-data\npm-debug.log
npm ERR! not ok code 0
```

**Comment by Twinkletoes** [comment]
debug-log sayeth:

```
0 info it worked if it ends with ok
1 verbose cli [ 'G:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'G:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.23
3 info using node@v0.10.31
4 verbose node symlink G:\Program Files\nodejs\\node.exe
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ 'F:\\Projects\\ember-data',
6 verbose install   [ 'aws-sdk',
6 verbose install     'bower',
6 verbose install     'broccoli-compile-modules',
6 verbose install     'broccoli-concat',
6 verbose install     'broccoli-defeatureify',
6 verbose install     'broccoli-env',
6 verbose install     'broccoli-es3-safe-recast',
6 verbose install     'broccoli-es6-module-transpiler',
6 verbose install     'broccoli-es6-transpiler',
6 verbose install     'broccoli-file-creator',
6 verbose install     'broccoli-file-mover',
6 verbose install     'broccoli-jshint',
6 verbose install     'broccoli-merge-trees',
6 verbose install     'broccoli-render-template',
6 verbose install     'broccoli-static-compiler',
6 verbose install     'broccoli-replace',
6 verbose install     'broccoli-uglify-js',
6 verbose install     'broccoli-wrap',
6 verbose install     'broccoli-yuidoc',
6 verbose install     'defeatureify',
6 verbose install     'ejs',
6 verbose install     'ember-cli',
6 verbose install     'ember-publisher',
6 verbose install     'es6-module-transpiler',
6 verbose install     'es6-module-transpiler-amd-formatter',
6 verbose install     'es6-module-transpiler-package-resolver',
6 verbose install     'git-repo-version',
6 verbose install     'testem',
6 verbose install     'yuidocjs' ] ]
7 info preinstall ember-data@1.0.0-beta.15-canary
8 warn package.json broccoli-es3-safe-recast@0.0.8 No README data
9 warn package.json es6-module-transpiler-package-resolver@1.0.1 No repository field.
10 warn package.json defeatureify@0.1.4 No description
11 warn package.json defeatureify@0.1.4 No repository field.
12 verbose readDependencies using package.json deps
13 verbose already installed skipping aws-sdk@~2.0.0-rc8 F:\Projects\ember-data
14 verbose already installed skipping bower@~1.3 F:\Projects\ember-data
15 verbose already installed skipping broccoli-compile-modules@^1.1.0 F:\Projects\ember-data
16 verbose already installed skipping broccoli-concat@0.0.12 F:\Projects\ember-data
17 verbose already installed skipping broccoli-defeatureify@^0.3.0 F:\Projects\ember-data
18 verbose already installed skipping broccoli-env@0.0.1 F:\Projects\ember-data
19 verbose already installed skipping broccoli-es3-safe-recast@0.0.8 F:\Projects\ember-data
20 verbose already installed skipping broccoli-es6-module-transpiler@^0.5.0 F:\Projects\ember-data
21 verbose already installed skipping broccoli-es6-transpiler@^0.1.0 F:\Projects\ember-data
22 verbose already installed skipping broccoli-file-creator@^0.1.0 F:\Projects\ember-data
23 verbose already installed skipping broccoli-file-mover@~0.2.0 F:\Projects\ember-data
24 verbose already installed skipping broccoli-jshint@^0.5.1 F:\Projects\ember-data
25 verbose already installed skipping broccoli-merge-trees@^0.1.4 F:\Projects\ember-data
26 verbose already installed skipping broccoli-render-template@0.0.3 F:\Projects\ember-data
27 verbose already installed skipping broccoli-static-compiler@^0.2.1 F:\Projects\ember-data
28 verbose already installed skipping broccoli-replace@~0.2.0 F:\Projects\ember-data
29 verbose already installed skipping broccoli-uglify-js@^0.1.3 F:\Projects\ember-data
30 verbose already installed skipping broccoli-wrap@0.0.2 F:\Projects\ember-data
31 verbose already installed skipping broccoli-yuidoc@^1.3.0 F:\Projects\ember-data
32 verbose already installed skipping defeatureify@~0.1.4 F:\Projects\ember-data
33 verbose already installed skipping ejs@^1.0.0 F:\Projects\ember-data
34 verbose already installed skipping ember-cli@^0.1.4 F:\Projects\ember-data
35 verbose already installed skipping ember-publisher@0.0.6 F:\Projects\ember-data
36 verbose already installed skipping es6-module-transpiler@^0.9.5 F:\Projects\ember-data
37 verbose already installed skipping es6-module-transpiler-amd-formatter@^0.2.4 F:\Projects\ember-data
38 verbose already installed skipping es6-module-transpiler-package-resolver@^1.0.1 F:\Projects\ember-data
39 verbose already installed skipping git-repo-version@0.0.2 F:\Projects\ember-data
40 verbose already installed skipping testem@^0.6.19 F:\Projects\ember-data
41 verbose already installed skipping yuidocjs@~0.3.46 F:\Projects\ember-data
42 silly resolved []
43 info build F:\Projects\ember-data
44 verbose linkStuff [ false, false, false, 'F:\\Projects' ]
45 info linkStuff ember-data@1.0.0-beta.15-canary
46 verbose linkBins ember-data@1.0.0-beta.15-canary
47 verbose linkMans ember-data@1.0.0-beta.15-canary
48 verbose rebuildBundles ember-data@1.0.0-beta.15-canary
49 verbose rebuildBundles [ '.bin',
49 verbose rebuildBundles   'aws-sdk',
49 verbose rebuildBundles   'bower',
49 verbose rebuildBundles   'broccoli-compile-modules',
49 verbose rebuildBundles   'broccoli-concat',
49 verbose rebuildBundles   'broccoli-defeatureify',
49 verbose rebuildBundles   'broccoli-env',
49 verbose rebuildBundles   'broccoli-es3-safe-recast',
49 verbose rebuildBundles   'broccoli-es6-module-transpiler',
49 verbose rebuildBundles   'broccoli-es6-transpiler',
49 verbose rebuildBundles   'broccoli-file-creator',
49 verbose rebuildBundles   'broccoli-file-mover',
49 verbose rebuildBundles   'broccoli-jshint',
49 verbose rebuildBundles   'broccoli-merge-trees',
49 verbose rebuildBundles   'broccoli-render-template',
49 verbose rebuildBundles   'broccoli-replace',
49 verbose rebuildBundles   'broccoli-static-compiler',
49 verbose rebuildBundles   'broccoli-uglify-js',
49 verbose rebuildBundles   'broccoli-wrap',
49 verbose rebuildBundles   'broccoli-yuidoc',
49 verbose rebuildBundles   'defeatureify',
49 verbose rebuildBundles   'ejs',
49 verbose rebuildBundles   'ember-cli',
49 verbose rebuildBundles   'ember-publisher',
49 verbose rebuildBundles   'es6-module-transpiler',
49 verbose rebuildBundles   'es6-module-transpiler-amd-formatter',
49 verbose rebuildBundles   'es6-module-transpiler-package-resolver',
49 verbose rebuildBundles   'git-repo-version',
49 verbose rebuildBundles   'testem',
49 verbose rebuildBundles   'yuidocjs' ]
50 info install ember-data@1.0.0-beta.15-canary
51 info postinstall ember-data@1.0.0-beta.15-canary
52 info prepublish ember-data@1.0.0-beta.15-canary
53 verbose unsafe-perm in lifecycle true
54 info ember-data@1.0.0-beta.15-canary Failed to exec prepublish script
55 error ember-data@1.0.0-beta.15-canary prepublish: `bower install && npm run-script dist`
55 error Exit status 1
56 error Failed at the ember-data@1.0.0-beta.15-canary prepublish script.
56 error This is most likely a problem with the ember-data package,
56 error not with npm itself.
56 error Tell the author that this fails on your system:
56 error     bower install && npm run-script dist
56 error You can get their info via:
56 error     npm owner ls ember-data
56 error There is likely additional logging output above.
57 error System Windows_NT 6.1.7601
58 error command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
59 error cwd F:\Projects\ember-data
60 error node -v v0.10.31
61 error npm -v 1.4.23
62 error code ELIFECYCLE
63 verbose exit [ 1, true ]
```

**Comment by stefanpenner** [comment]
@Twinkletoes your using an extremely old version of NPM, please upgrade to 2.1.x

**Comment by Twinkletoes** [comment]
Trying that now...

**Comment by Twinkletoes** [comment]
After updating NPM I get this (after successful npm install logs)

```
> ember-data@1.0.0-beta.15-canary dist F:\Projects\ember-data
> ember build --environment=production

version: 0.1.5
Cleanup error.
ENOTEMPTY, directory not empty 'F:\Projects\ember-data\tmp\static_compiler-tmp_d
est_dir-zJFNfJXk.tmp\ember-data-jshint\system'
Error: ENOTEMPTY, directory not empty 'F:\Projects\ember-data\tmp\static_compile
r-tmp_dest_dir-zJFNfJXk.tmp\ember-data-jshint\system'
  at Object.fs.rmdirSync (fs.js:623:18)
  at rmkidsSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\no
de_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js
:247:11)
  at rmdirSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\nod
e_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:
237:7)
  at fixWinEPERMSync (F:\Projects\ember-data\node_modules\broccoli-static-compil
er\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimr
af.js:150:5)
  at rimrafSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\no
de_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js
:216:26)
  at F:\Projects\ember-data\node_modules\broccoli-static-compiler\node_modules\b
roccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\no
de_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js
:244:26)
  at rmdirSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\nod
e_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:
237:7)
  at fixWinEPERMSync (F:\Projects\ember-data\node_modules\broccoli-static-compil
er\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimr
af.js:150:5)
  at rimrafSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\no
de_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js
:216:26)
  at F:\Projects\ember-data\node_modules\broccoli-static-compiler\node_modules\b
roccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
  at Array.forEach (native)
  at rmkidsSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\no
de_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js
:244:26)
  at rmdirSync (F:\Projects\ember-data\node_modules\broccoli-static-compiler\nod
e_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimraf.js:
237:7)
  at fixWinEPERMSync (F:\Projects\ember-data\node_modules\broccoli-static-compil
er\node_modules\broccoli-writer\node_modules\quick-temp\node_modules\rimraf\rimr
af.js:150:5)
  at Function.rimrafSync [as sync] (F:\Projects\ember-data\node_modules\broccoli
-static-compiler\node_modules\broccoli-writer\node_modules\quick-temp\node_modul
es\rimraf\rimraf.js:216:26)
  at Object.remove (F:\Projects\ember-data\node_modules\broccoli-static-compiler
\node_modules\broccoli-writer\node_modules\quick-temp\index.js:26:12)
  at StaticCompiler.Writer.cleanup (F:\Projects\ember-data\node_modules\broccoli
-static-compiler\node_modules\broccoli-writer\index.js:18:13)
  at cleanupTree (F:\Projects\ember-data\node_modules\ember-cli\node_modules\bro
ccoli\lib\builder.js:128:19)
  at promise.then.then.results.(anonymous function) (F:\Projects\ember-data\node
_modules\ember-cli\node_modules\broccoli\node_modules\promise-map-series\index.j
s:8:27)
  at $$$internal$$tryCatch (F:\Projects\ember-data\node_modules\ember-cli\node_m
odules\rsvp\dist\rsvp.js:490:16)
  at $$$internal$$invokeCallback (F:\Projects\ember-data\node_modules\ember-cli\
node_modules\rsvp\dist\rsvp.js:502:17)
  at $$$internal$$publish (F:\Projects\ember-data\node_modules\ember-cli\node_mo
dules\rsvp\dist\rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (F:\Projects\ember-data\node_mo
dules\ember-cli\node_modules\rsvp\dist\rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)

Build failed.
EEXIST, file already exists 'F:\Projects\ember-data\tmp\static_compiler-tmp_dest
_dir-qLKs9aQS.tmp'
Error: EEXIST, file already exists 'F:\Projects\ember-data\tmp\static_compiler-t
mp_dest_dir-qLKs9aQS.tmp'
  at Object.fs.mkdirSync (fs.js:653:18)
  at Object.copyDereferenceSync (F:\Projects\ember-data\node_modules\broccoli-st
atic-compiler\node_modules\symlink-or-copy\node_modules\copy-dereference\index.j
s:19:8)
  at symlinkWindows (F:\Projects\ember-data\node_modules\broccoli-static-compile
r\node_modules\symlink-or-copy\index.js:92:13)
  at symlinkOrCopySync (F:\Projects\ember-data\node_modules\broccoli-static-comp
iler\node_modules\symlink-or-copy\index.js:56:5)
  at StaticCompiler._copy (F:\Projects\ember-data\node_modules\broccoli-static-c
ompiler\index.js:59:3)
  at F:\Projects\ember-data\node_modules\broccoli-static-compiler\index.js:25:12

  at $$$internal$$tryCatch (F:\Projects\ember-data\node_modules\ember-cli\node_m
odules\rsvp\dist\rsvp.js:490:16)
  at $$$internal$$invokeCallback (F:\Projects\ember-data\node_modules\ember-cli\
node_modules\rsvp\dist\rsvp.js:502:17)
  at $$$internal$$publish (F:\Projects\ember-data\node_modules\ember-cli\node_mo
dules\rsvp\dist\rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (F:\Projects\ember-data\node_mo
dules\ember-cli\node_modules\rsvp\dist\rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:345:15)


npm ERR! ember-data@1.0.0-beta.15-canary dist: `ember build --environment=produc
tion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary dist script.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment=production
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "dist"
npm ERR! cwd F:\Projects\ember-data
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\Projects\ember-data\npm-debug.log
npm ERR! not ok code 0

npm ERR! ember-data@1.0.0-beta.15-canary prepublish: `bower install && npm run-s
cript dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary prepublish script.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && npm run-script dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd F:\Projects\ember-data
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\Projects\ember-data\npm-debug.log
npm ERR! not ok code 0
```

**Comment by Twinkletoes** [comment]
tried a cache clean and that got rid of the ENOTEMPTY but the EEXIST still happens

**Comment by stefanpenner** [comment]
> npm ERR! npm -v 1.4.23

this claims your NPM version is still old

**Comment by stefanpenner** [comment]
Their is likely something else going on as it looks like something is potentially retaining your file handles in the tmp dir. Maybe some file-watching/anti-virus/search indexing/text-editor is retaining. Some of [this](http://www.ember-cli.com/#solving-performance-issues-on-windows) may be relevant.

Beyond spinning up a windows VM (which i may have time for on Sunday) I will likely not be able to help much more.

Anyways, I should suggest getting to the most recent NPM, blowing away all tmp dirs and caches and trying again.

**Comment by stefanpenner** [comment]
an idea to help mitigate pain for theoretical windows contributors: https://github.com/emberjs/data/issues/2654

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/2655 seems to validate the issue you are having. Unfortunately I don't have time right now to dig in further.

**Comment by Twinkletoes** [comment]
npm -v was giving me 1.4 even after a successful npm -g install npm

Solution was that it was installing it into a subfolder of node_modules. I copied the subfolder and pasted over the master npm folder. Now I get 2.1 as npm -v

Try this method of updating the appveyor install? The nodejs installer comes with npm 1.4.

**Comment by Twinkletoes** [comment]
Unfortunately the correct version of npm doesn't help us...

F:\Projects\ember-data>npm install
npm WARN package.json broccoli-es3-safe-recast@0.0.8 No README data
npm WARN package.json defeatureify@0.1.4 No description
npm WARN package.json defeatureify@0.1.4 No repository field.
npm WARN package.json es6-module-transpiler-package-resolver@1.0.1 No repository
 field.

> ember-data@1.0.0-beta.15-canary prepublish F:\Projects\ember-data
> bower install && npm run-script dist

bower extra-resolution      Unnecessary resolution: handlebars#>= 2.0.0 < 3.0.0

> ember-data@1.0.0-beta.15-canary dist F:\Projects\ember-data
> ember build --environment=production

version: 0.1.5
Build failed.
EEXIST, file already exists 'F:\Projects\ember-data\tests'
Error: EEXIST, file already exists 'F:\Projects\ember-data\tests'
  at Object.fs.symlinkSync (fs.js:742:18)
  at symlinkWindows (F:\Projects\ember-data\node_modules\broccoli-static-compile
r\node_modules\symlink-or-copy\index.js:90:16)
  at symlinkOrCopySync (F:\Projects\ember-data\node_modules\broccoli-static-comp
iler\node_modules\symlink-or-copy\index.js:56:5)
  at StaticCompiler._copy (F:\Projects\ember-data\node_modules\broccoli-static-c
ompiler\index.js:59:3)
  at F:\Projects\ember-data\node_modules\broccoli-static-compiler\index.js:25:12

  at $$$internal$$tryCatch (F:\Projects\ember-data\node_modules\ember-cli\node_m
odules\rsvp\dist\rsvp.js:490:16)
  at $$$internal$$invokeCallback (F:\Projects\ember-data\node_modules\ember-cli\
node_modules\rsvp\dist\rsvp.js:502:17)
  at $$$internal$$publish (F:\Projects\ember-data\node_modules\ember-cli\node_mo
dules\rsvp\dist\rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (F:\Projects\ember-data\node_mo
dules\ember-cli\node_modules\rsvp\dist\rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:354:15)


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "dist"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE
npm ERR! ember-data@1.0.0-beta.15-canary dist: `ember build --environment=produc
tion`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary dist script 'ember build
--environment=production'.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment=production
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Projects\ember-data\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE
npm ERR! ember-data@1.0.0-beta.15-canary prepublish: `bower install && npm run-s
cript dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data@1.0.0-beta.15-canary prepublish script 'bower
install && npm run-script dist'.
npm ERR! This is most likely a problem with the ember-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && npm run-script dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Projects\ember-data\npm-debug.log

**Comment by eoinkelly** [comment]
I just replicated this in a Win7 VM using node 0.10.35 and npm 1.4.28 (the version installed by the node installer). 

The problem is that `ember build --environment=production` is failing - this command is run by the [npm prepublish script](https://docs.npmjs.com/misc/scripts) which despite the name is also run during `npm install`.

To be clear: the problem is not npm related - you can trigger the error by running `ember build --environment=production` or simply `ember build`

This is the error I recieve:

```

version: 0.1.5
Build failed.
EEXIST, file already exists 'C:\Users\IEUser\Desktop\data\tmp\static_compiler-tmp_dest_dir-wUdkysuk.tmp'
Error: EEXIST, file already exists 'C:\Users\IEUser\Desktop\data\tmp\static_compiler-tmp_dest_dir-wUdkysuk.tmp'
  at Object.fs.mkdirSync (fs.js:654:18)
  at Object.copyDereferenceSync (C:\Users\IEUser\Desktop\data\node_modules\broccoli-static-compiler\node_modules\symlink-or-copy\node_modules\copy-dereference\index.js:19:8)
  at symlinkWindows (C:\Users\IEUser\Desktop\data\node_modules\broccoli-static-compiler\node_modules\symlink-or-copy\index.js:92:13)
  at symlinkOrCopySync (C:\Users\IEUser\Desktop\data\node_modules\broccoli-static-compiler\node_modules\symlink-or-copy\index.js:56:5)
  at StaticCompiler._copy (C:\Users\IEUser\Desktop\data\node_modules\broccoli-static-compiler\index.js:59:3)
  at C:\Users\IEUser\Desktop\data\node_modules\broccoli-static-compiler\index.js :25:12
  at $$$internal$$tryCatch (C:\Users\IEUser\Desktop\data\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:490:16)
  at $$$internal$$invokeCallback (C:\Users\IEUser\Desktop\data\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:502:17)
  at $$$internal$$publish (C:\Users\IEUser\Desktop\data\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:473:11)
  at Object.$$rsvp$asap$$flush [as _onImmediate] (C:\Users\IEUser\Desktop\data\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1581:9)
  at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I do not see _any_ files in the `C:\Users\IEUser\Desktop\data\tmp` after the run.

The only `timers.js` (see last line of stack) I can find is in `./node_modules/yuidocjs/node_modules/yui/timers/timers.js` which seems to indicate that the problem is YUIdoc related. However I get the same error after removing all references to YUI from the `Brocfile.js`.

I'm afraid I don't have time to dig any deeper this morning. 
HTH
/Eoin/

**Comment by igorT** [comment]
It appears that we fixed the Windows CI, so this shouldn't be an issue anymore, please reopen if it still is.
