### ISSUE TITLE
DS.RESTSerializer not extending correctly / models not loaded correctly

### ISSUE THREAD

**Issue by nichoth** [emberjs/data#2746]
I made a serializer via ember-cli, and when overriding the `normalize` method like so, it throws an error:

```js
// serializers/node.js
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
  normalize: function(type, hash, property) {
    return this._super(arguments);
  },
});
```

```
Error while processing route: node undefined is not a function TypeError: undefined is not a function
    at __exports__.default.Ember.Object.extend.normalizeAttributes (http://0.0.0.0:4200/assets/vendor.js:66484:16)
    at JSONSerializer.extend.normalize (http://0.0.0.0:4200/assets/vendor.js:67541:14)
    at apply (http://0.0.0.0:4200/assets/vendor.js:32885:27)
    at superWrapper (http://0.0.0.0:4200/assets/vendor.js:32457:15)
    at apply (http://0.0.0.0:4200/assets/vendor.js:32885:27)
    at superFunction [as _super] (http://0.0.0.0:4200/assets/vendor.js:29315:15)
    at __exports__.default.DS.RESTSerializer.extend.normalize (http://0.0.0.0:4200/assets/bookmark.js:352:21)
    at apply (http://0.0.0.0:4200/assets/vendor.js:32887:27)
    at superWrapper [as normalize] (http://0.0.0.0:4200/assets/vendor.js:32457:15)
    at JSONSerializer.extend.extractSingle (http://0.0.0.0:4200/assets/vendor.js:67653:34)
```

The undefined function is `eachAttribute` on the `type` parameter. It is called in `normalizeAttributes` in the serializer. Async issue?

**Comment by fivetanley** [comment]
`arguments` in javascript is an array-like object that allows to reuse arguments easily. unless the function signature expects an array-like, you want to use Function.prototype.apply, like you want to use here:

```javascript
return this._super.apply(this, arguments);
```

or you can pass all the args manually:

```javascript
return this._super(type, hash, property);
```

**Comment by nichoth** [comment]
duh. Ha ha. Spent at least an hour with this.
