### ISSUE TITLE
depracation warnings

### ISSUE THREAD

**Issue by spruce** [emberjs/data#2893]
Hey,
I don't know where else to post this. So here it goes:
After upgrading to ember-data: 1.0.0-beta15 , ember 1.11.0-beta5 and ember-cli 0.2.0 I got when saving a model with some polymorphic properties these depractations:
```
DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead. ember.debug.js:5236 
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at Ember.defineProperty.get [as constructor] (http://localhost:4200/assets/vendor.js:67373:21)
        at CallSiteToString (native)
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:938:20)
        at ember$data$lib$system$snapshot$$Snapshot.get (http://localhost:4200/assets/vendor.js:67654:15)
        at ember$data$lib$system$snapshot$$Snapshot.unknownProperty (http://localhost:4200/assets/vendor.js:67683:21)
        at Object.get (http://localhost:4200/assets/vendor.js:26122:20)
        at serializePolymorphicType (http://localhost:4200/assets/project.js:3085:40)
        at ember$data$lib$system$serializer$$default.extend.serializeBelongsTo (http://localhost:4200/assets/vendor.js:63197:18)

2 DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead. ember.debug.js:5236 
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at Ember.defineProperty.get [as constructor] (http://localhost:4200/assets/vendor.js:67373:21)
        at CallSiteToString (native)
        at Ember.default.deprecate (http://localhost:4200/assets/vendor.js:15765:64)
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at ember$data$lib$system$snapshot$$Snapshot.get (http://localhost:4200/assets/vendor.js:67654:15)
        at ember$data$lib$system$snapshot$$Snapshot.unknownProperty (http://localhost:4200/assets/vendor.js:67683:21)
        at Object.get (http://localhost:4200/assets/vendor.js:26122:20)
        at serializePolymorphicType (http://localhost:4200/assets/project.js:3085:40)

 DEPRECATION: Using DS.Snapshot.get() is deprecated. Use .attr(), .belongsTo() or .hasMany() instead. ember.debug.js:5236
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at ember$data$lib$system$snapshot$$Snapshot.get (http://localhost:4200/assets/vendor.js:67654:15)
        at ember$data$lib$system$snapshot$$Snapshot.unknownProperty (http://localhost:4200/assets/vendor.js:67683:21)
        at Object.get (http://localhost:4200/assets/vendor.js:26122:20)
        at serializePolymorphicType (http://localhost:4200/assets/project.js:3085:40)
        at ember$data$lib$system$serializer$$default.extend.serializeBelongsTo (http://localhost:4200/assets/vendor.js:63197:18)
        at null.<anonymous> (http://localhost:4200/assets/vendor.js:63069:18)
        at http://localhost:4200/assets/vendor.js:73012:20
        at Map.forEach.cb (http://localhost:4200/assets/vendor.js:24051:11)

 DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead. ember.debug.js:5236
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at Ember.defineProperty.get [as constructor] (http://localhost:4200/assets/vendor.js:67373:21)
        at serializePolymorphicType (http://localhost:4200/assets/project.js:3089:27)
        at ember$data$lib$system$serializer$$default.extend.serializeBelongsTo (http://localhost:4200/assets/vendor.js:63197:18)
        at null.<anonymous> (http://localhost:4200/assets/vendor.js:63069:18)
        at http://localhost:4200/assets/vendor.js:73012:20
        at Map.forEach.cb (http://localhost:4200/assets/vendor.js:24051:11)
        at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:23842:11)
        at Map.forEach (http://localhost:4200/assets/vendor.js:24055:18)

 DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead. ember.debug.js:5236
        at Object.__exports__.default.EmberObject.extend.replaceDeprecate.Ember.deprecate (<anonymous>:970:38)
        at Ember.defineProperty.get [as constructor] (http://localhost:4200/assets/vendor.js:67373:21)
        at serializePolymorphicType (http://localhost:4200/assets/project.js:3090:72)
        at ember$data$lib$system$serializer$$default.extend.serializeBelongsTo (http://localhost:4200/assets/vendor.js:63197:18)
        at null.<anonymous> (http://localhost:4200/assets/vendor.js:63069:18)
        at http://localhost:4200/assets/vendor.js:73012:20
        at Map.forEach.cb (http://localhost:4200/assets/vendor.js:24051:11)
        at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:23842:11)
        at Map.forEach (http://localhost:4200/assets/vendor.js:24055:18)
```

What I noticed 2 different deprecations:  
``` DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.  ```
and 
``` DEPRECATION: Using DS.Snapshot.get() is deprecated. Use .attr(), .belongsTo() or .hasMany() instead. ```

Someone also ran into these depracations: http://stackoverflow.com/questions/29052574/ember-cli-broken-by-new-release-of-ember-data

How can I get rid of these depracations, or is there a problem on your side?

**Comment by bmac** [comment]
Hi @spruce. Are you using a custom serializer in your application?

**Comment by spruce** [comment]
dang. Yes, Didn't think of serializers only adapters :(
The only difference is I somehow have an old fix for the serializer not correctly encoding polymorphic async belongsTos. Like this: 
```
import DS from 'ember-data';
import Ember from 'ember';

export default DS.RESTSerializer.extend({
  serializePolymorphicType: function(record, json, relationship) {
    var key = relationship.key;
    var belongsTo = Ember.belongsTo(record, key);
    key = this.keyForAttribute ? this.keyForAttribute(key) : key;
    if(Ember.isNone(belongsTo)) {
      json[key + "Type"] = null;
    } else if(belongsTo.type.typeKey) {
      json[key + "Type"] = Ember.String.camelize(belongsTo.type.typeKey);
    } else {
      // probably a async polymorphic belongsTo
      json[key + "Type"] = Ember.String.camelize(belongsTo.content.type.typeKey);
    }
  }
});
```

Is this still needed or can I delete it completly?

**Comment by bmac** [comment]
I believe you should be able to delete it completely. The warnings are coming from a change where instead of a `record` all serializers are now given a `snapshot` instance. The advantage of a `snapshot` is its isn't allowed to have side effects when accessing relationships so it simplifies many cases like the one above where before you would need to do something different for async vs non-async.

**Comment by spruce** [comment]
Nice thanks :+1:
