### ISSUE TITLE
1.0.0-beta.16 is looking for an application model

### ISSUE THREAD

**Issue by kamal** [emberjs/data#2925]
```
Error: No model was found for 'application'
    at new Error (native)
    at Error.EmberError (http://localhost:7357/assets/vendor.js:21836:23)
    at ember$data$lib$system$store$$Service.extend.modelFor (http://localhost:7357/assets/vendor.js:78603:19)
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:7357/assets/vendor.js:78974:21)
    at DS.Store.reopen.usingFixtureAdapter (http://localhost:7357/assets/test-support.js:5973:26)
    at DS.Store.reopen.pushPayload (http://localhost:7357/assets/test-support.js:6204:16)
    at superWrapper [as pushPayload] (http://localhost:7357/assets/vendor.js:27582:22)
    at http://localhost:7357/assets/garaje.js:5901:22
    at tryCatch (http://localhost:7357/assets/vendor.js:59834:16)
    at invokeCallback (http://localhost:7357/assets/vendor.js:59846:17)
```

The usage that caused this was an innocent `this.store.pushPayload('subscription', data)`.

**Comment by Kuzirashi** [comment]
I came across this when using:
`store.adapterFor('application').buildURL(...)`
It previously worked but now I had to use some real Ember Data model instead of `application`.

**Comment by bmac** [comment]
Thanks for reporting this issue. I've opened a pr https://github.com/emberjs/data/pull/2926 to attempt to fix it. For now you can work around this issue in beta.16 by doing `store.lookupAdapter('application')`. 

@kamal It looks like some library you are using has opened up `store.pushPayload` and is likely calling `store.adapterFor('application')`.

**Comment by kamal** [comment]
@bmac you're right. ember-data-factory-guy does reopen pushPayload
