### ISSUE TITLE
Model attribute named 'error' causes exception

### ISSUE THREAD

**Issue by ZebraFlesh** [emberjs/data#3449]
Given the following model definition:

````
import DS from 'ember-data';

export default DS.Model.extend({
  state: DS.attr('string'),
  error: DS.attr('string'),
  progress: DS.attr('number'),
  complete: DS.attr('boolean', {defaultValue: false}),
  canceling: DS.attr('boolean', {defaultValue: false})
});
````

I encountered the following exception when upgrading from ember-data 1.0.0-beta-19.1 to 1.13.4:

````
Error: Attempted to handle event 'didSetProperty' on <task-status:16> while in state root.loading. Called with {name: error, oldValue: undefined, originalValue: undefined, value: null}.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25661:21)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel._unhandledEvent (http://localhost:4200/assets/vendor.js:80504:15)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.send (http://localhost:4200/assets/vendor.js:80381:16)
    at ember$new$computed$lib$main$$default.set (http://localhost:4200/assets/vendor.js:83921:33)
    at Descriptor.computedPropertySet [as _set] (http://localhost:4200/assets/vendor.js:23967:20)
    at Descriptor.computedPropertySetWithSuspend [as set] (http://localhost:4200/assets/vendor.js:23933:12)
    at new Class (http://localhost:4200/assets/vendor.js:46723:20)
    at Function.ClassMixinProps.create (http://localhost:4200/assets/vendor.js:47181:14)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.materializeRecord (http://localhost:4200/assets/vendor.js:80194:33)
````

Once I renamed my model's "error" attribute to "errorMsg", the exception no longer occurred.

**Comment by visoft** [comment]
I'm seeing the same problem.

**Comment by bmac** [comment]
I'm surprised this error started occurring with "1.13.4". Ember Data has had an error property on `DS.Model` for a long time. @tchak any idea whats going on here?

**Comment by tchak** [comment]
@bmac no it have not... It is a new one. Maybe it was a bad idea. I am not exactly sure what would be the right thing to do here.

**Comment by kenips** [comment]
@tchak @bmac broken here https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/internal-model.js#L116 introduced by 893e2af813c16786ba6d9296cf3aa27b7407872e

**Comment by kenips** [comment]
@tchak oh sorry didn't see your commit above.
