### ISSUE TITLE
DS.Model type property name in non-polymorphic models

### ISSUE THREAD

**Issue by splattne** [emberjs/data#3702]
I upgraded Ember data from 1.13.x to **1.13.11** in my app and got a weird error in my serializer (REST) in decimalizing a number property's value.

I debugged it and saw, that it's related to the fact that I use a property named `type` in the model. It's just a numeric value, it's not a  polymorphic subclass identifier.

    type: DS.attr('number')

The same code used to work in a prior Ember data version. Is this a bug? If not, is there some documentation on this? I have a lot of model which have a `type` property.

**Comment by wecc** [comment]
I suspect this is due to the new Serializer API and how we rewrote some of the polymorphic parts. Would you be able to provide a trace and/or failing JSBin?

**Comment by splattne** [comment]
Errata: I'm using Ember data **1.13.11** (not .9) and Ember 1.13.9.

Here's the trace from the exception in my app (str is a number with value 1)

    TypeError: str.replace is not a function
     at Object.func (http://localhost:21002/Scripts/ember/ember.debug.js:40173:16)
     at Object.Cache.get (http://localhost:21002/Scripts/ember/ember.debug.js:14063:36)
     at decamelize (http://localhost:21002/Scripts/ember/ember.debug.js:40210:29)
     at Object.func (http://localhost:21002/Scripts/ember/ember.debug.js:40130:12)
     at Object.Cache.get (http://localhost:21002/Scripts/ember/ember.debug.js:14063:36)
     at Object.dasherize (http://localhost:21002/Scripts/ember/ember.debug.js:40214:35)
     at ember$data$lib$system$normalize$model$name$$normalizeModelName (http://localhost:21002/Scripts/ember/ember-data.js:2548:27)
     at ember$data$lib$serializers$json$serializer$$default.extend.modelNameFromPayloadKey (http://localhost:21002/Scripts/ember/ember-data.js:6551:67)
     at ember$data$lib$serializers$json$serializer$$default.extend._normalizePolymorphicRecord (http://localhost:21002/Scripts/ember/ember-data.js:6033:50)
     at null. (http://localhost:21002/Scripts/ember/ember-data.js:6013:51)

**Comment by amk221** [comment]
I think I've created a duplicate issue
https://github.com/emberjs/data/issues/3731

**Comment by bmac** [comment]
I believe this issue has been fixed. There have been several bugfixes in the serializers to fix edge cases around the type property name in non-polymorphic models.
