### ISSUE TITLE
Ember Data with (heavily nested) embedded JSON fails

### ISSUE THREAD

**Issue by rockinho** [emberjs/data#3710]
Hi there,

i'm trying to migrate my Ember 1.12.x App to Ember 1.13.8 and im going crazy with our JSON and Ember Data.

I really need help, i tryed out so many things and no progress :(

I have Nested JSON Payload like this:

```
{  
   "dashboard":[  
      {  
         "elementBeanList":[  
            {  
               "fieldBeanList":[  
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.Integer"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  }
               ],
               "elementClassId":"xxx",
               "elementBeanList":[  

               ],
               "count":null,
               "link":"5",
               "linkList":[  
                  {  
                     "id":"xxx",
                     "value":"xxx"
                  }
               ]
            },
            {  
               "fieldBeanList":[  
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.Integer"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  }
               ],
               "elementClassId":"xxx",
               "elementBeanList":[  

               ],
               "count":null,
               "link":"1",
               "linkList":[  
                  {  
                     "id":"xxx",
                     "value":"xxx"
                  },
                  {  
                     "id":"xxx",
                     "value":"xxx"
                  }
               ]
            },
            {  
               "fieldBeanList":[  
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.Integer"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  },
                  {  
                     "fieldName":null,
                     "fieldType":"java.lang.String"
                  }
               ],
               "elementClassId":"xxx",
               "elementBeanList":[  

               ],
               "count":null,
               "link":"2",
               "linkList":[  
                  {  
                     "id":"xxx",
                     "value":"xxx"
                  },
                  {  
                     "id":"xxx",
                     "value":"xxx"
                  }
               ]
            }
         ]
      }
   ],
   "titel":"Dashboard"
}
```

And my models:

```
dashboard: 
export default DS.Model.extend({
    elementBeanList: DS.hasMany('elementbeanlist')
});

elementbeanlist: 
export default DS.Model.extend({
    fieldBeanList: DS.hasMany('fieldbeanlist'),
    elementBeanList: DS.hasMany('elementbeanlist', {inverse: null}),
    elementClassId: DS.attr('string'),
    link: DS.attr('string'),
    linkList: DS.attr(),
    count: DS.attr(),
});

fieldbeanlist:
export default DS.Model.extend({
    fieldName:DS.attr('string'),
    fieldType:DS.attr('string')
});
```

And i modified the serializer:

```
dashboardSerializer: 

export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin,{
    attrs: {
        elementBeanList: { embedded: 'always' },
        fieldbeanlist: { embedded: 'always' },
    },
    normalizePayload: function(payload) {
        console.log("DashboardSerializer > normalizePayload");

        if(payload.elementBeanWrapper){
          payload.dashboard = payload.elementBeanWrapper;
          delete payload.elementBeanWrapper;
            }
         return payload;
     }
});

```

When i try transition to the Dashboard Route i get this error and dont know how to solve it!

I thank you in advance for your help!

```
Error while processing route: dashboard Assertion Failed: You must include an `id` for elementbeanlist in an object passed to `push` Error: Assertion Failed: You must include an `id` for elementbeanlist in an object passed to `push`
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26452:21)
    at Object._emberMetalCore.default.assert (http://localhost:4200/assets/vendor.js:15896:13)
    at ember$data$lib$system$store$$Service.extend.push (http://localhost:4200/assets/vendor.js:83089:17)
    at http://localhost:4200/assets/vendor.js:85367:17
    at Array.forEach (native)
    at Ember.Mixin.create._extractEmbeddedHasMany (http://localhost:4200/assets/vendor.js:85365:68)
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:85330:22)
    at http://localhost:4200/assets/vendor.js:86400:20
    at Map.forEach.cb (http://localhost:4200/assets/vendor.js:28210:11)logError @ ember.debug.js:29271defaultActionHandlers.error @ ember.debug.js:29214triggerEvent @ ember.debug.js:29327trigger @ ember.debug.js:55740Transition.trigger @ ember.debug.js:55554(anonymous function) @ ember.debug.js:55374tryCatch @ ember.debug.js:56151invokeCallback @ ember.debug.js:56166publish @ ember.debug.js:56134publishRejection @ ember.debug.js:56068(anonymous function) @ ember.debug.js:32577Queue.invoke @ ember.debug.js:910Queue.flush @ ember.debug.js:974DeferredActionQueues.flush @ ember.debug.js:770Backburner.end @ ember.debug.js:160Backburner.run @ ember.debug.js:228run @ ember.debug.js:20238ember$data$lib$system$adapter$$default.extend.ajax.Ember.RSVP.Promise.hash.success @ rest-adapter.js:831jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260done @ jquery.js:9314jQuery.ajaxTransport.send.callback @ jquery.js:9718XMLHttpRequest.send (async)jQuery.ajaxTransport.send @ jquery.js:9664jQuery.extend.ajax @ jquery.js:9215ember$data$lib$system$adapter$$default.extend.ajax @ rest-adapter.js:861initializePromise @ ember.debug.js:56200Promise @ ember.debug.js:57742ember$data$lib$system$adapter$$default.extend.ajax @ rest-adapter.js:810ember$data$lib$system$adapter$$default.extend.query @ rest-adapter.js:441ember$data$lib$system$store$finders$$_query @ finders.js:174ember$data$lib$system$store$$Service.extend.query @ store.js:1000ember$data$lib$system$store$$Service.extend.find @ store.js:443model @ dashboard.js:13_emberRuntimeSystemObject.default.extend.deserialize @ ember.debug.js:27858applyHook @ ember.debug.js:55858HandlerInfo.runSharedModelHook @ ember.debug.js:53943_routerUtils.subclass.getModel @ ember.debug.js:54142i @ ember.debug.js:55726tryCatch @ ember.debug.js:56151invokeCallback @ ember.debug.js:56166publish @ ember.debug.js:56134(anonymous function) @ ember.debug.js:32577Queue.invoke @ ember.debug.js:910Queue.flush @ ember.debug.js:974DeferredActionQueues.flush @ ember.debug.js:770Backburner.end @ ember.debug.js:160Backburner.run @ ember.debug.js:228Backburner.join @ ember.debug.js:263run.join @ ember.debug.js:20280run.bind @ ember.debug.js:20343jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503
```

**Comment by bmac** [comment]
Hi @rockinho. https://stackoverflow.com/ and http://discuss.emberjs.com/ are usually more effective channels for this kind of support. Looking over your payload quickly it looks like your `dashboard` model is missing an id property. Ember Data requires every model have a unique (per type) id property so it can keep track of the record in its store. If your serialized record is using a different key for its id (for example your `elementBeanList` class appears to have a unique `elementClassId` property) you can set the [primaryKey](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#property_primaryKey) property on the serializer for that type.
