### ISSUE TITLE
Failing to build on master branch when running npm test.

### ISSUE THREAD

**Issue by arenoir** [emberjs/data#4572]
All 6 scenarios fail when running the test suite.  I am getting the following build error.

```
Build failed.
The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
TypeError: Cannot set property 'patches' of undefined
    at Funnel.processFilters (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/broccoli-funnel/index.js:277:33)
    at Funnel.build (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/broccoli-funnel/index.js:202:10)
    at /Users/aaronrenoir/Workspace/arenoir/data/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/broccoli-funnel/index.js:56:10)
    at EmberAddon.EmberApp.index (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/broccoli/ember-app.js:641:15)
    at EmberAddon.EmberApp.toArray (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/broccoli/ember-app.js:1605:10)
    at EmberAddon.EmberApp.toTree (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/broccoli/ember-app.js:1628:30)
    at module.exports (/Users/aaronrenoir/Workspace/arenoir/data/ember-cli-build.js:50:21)
    at CoreObject.setupBroccoliBuilder (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.init (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/models/builder.js:54:10)
    at CoreObject.superWrapper [as init] (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/core-object/core-object.js:32:33)
    at CoreObject.run (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/ember-cli/lib/commands/test.js:164:27)
    at lib$rsvp$$internal$$tryCatch (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/aaronrenoir/Workspace/arenoir/data/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

System Version: OS X 10.11.6 (15G1004)
npm version 3.10.9
node version v6.7.0

**Comment by bmac** [comment]
Thanks for reporting this issue @arenoir. I believe master has been fixed by https://github.com/emberjs/data/pull/4574 and this error is no longer present.
