### ISSUE TITLE
JSON-API AssertionError with JSONSerializer

### ISSUE THREAD

**Issue by maha99tests** [emberjs/data#4608]
I've switched my serializer by adding the application serializer file -> app/serializers/application.js

    import DS from 'ember-data';

    export default DS.JSONSerializer.extend({
    });

and I'm using the RESTAdapter, customized at app/adapters/application.js

    export default DS.RESTAdapter.extend({
       host: 'http://60.60.60.60:3000/'
    });

But when my server fails with validation errors with a 422, I get an assertion error that the errors should be in the JSON API format

    ember.debug.js:19157 Error: Assertion Failed: `AdapterError` expects json-api formatted errors array.
    at new Error (native)
    at Error.EmberError (http://60.60.60.60:4200/assets/vendor.js:29613:21)
    at assert (http://60.60.60.60:4200/assets/vendor.js:17311:13)
    at Object.assert (http://60.60.60.60:4200/assets/vendor.js:29425:34)
    at assert (http://60.60.60.60:4200/assets/vendor.js:66105:37)
    at ErrorClass (http://60.60.60.60:4200/assets/vendor.js:77100:41)
    at Class.handleResponse (http://60.60.60.60:4200/assets/vendor.js:78331:16)
    at ajaxError (http://60.60.60.60:4200/assets/vendor.js:78852:25)
    at Class.hash.error (http://60.60.60.60:4200/assets/vendor.js:78426:23)
    at fire (http://60.60.60.60:4200/assets/vendor.js:3617:31)

My error payload is

```
{
	"errors": {
		"email": ["can't be blank"],
		"password": ["can't be blank"],
		"first_name": ["can't be blank"],
		"last_name": ["can't be blank"],
		"title": ["can't be blank", "Should be Mr or Ms"]
	}
}
```

**Comment by urbany** [comment]
Hey, if you use the JSONAPI serializer the `errors` must be an array of objects.
Check these examples: http://jsonapi.org/examples/#error-objects-basics

**Comment by maha99tests** [comment]
But i'm using the JSONSerializer by customizing the application serializer - 

```
export default DS.JSONSerializer.extend({
});
```

Am I missing something?

**Comment by urbany** [comment]
I think your error payload should be something like:

```json
{
    "errors": {
        {
          "source": { "pointer": "/data/attributes/email" },
          "detail": "can't be blank"
        },
        {
          "source": { "pointer": "/data/attributes/password" },
          "detail": "can't be blank"
        },
        {
          "source": { "pointer": "/data/attributes/first-name" },
          "detail": "can't be blank"
        },
        {
          "source": { "pointer": "/data/attributes/last-name" },
          "detail": "can't be blank"
        },
        {
          "source": { "pointer": "/data/attributes/title" },
          "detail": "can't be blank, should be Mr or Ms"
        }
    }
}
```
