### ISSUE TITLE
Ember data 2.11.2 Error: You attempted to access "modelName" on a factory manager created by container#factoryFor

### ISSUE THREAD

**Issue by ming-codes** [emberjs/data#4822]
```
Error: You attempted to access "modelName" on a factory manager created by container#factoryFor. "modelName" is not a member of a factory manager.
 at Object.get (http://localhost:7357/assets/vendor.js:139535:21) at Class._modelFactoryFor (http://localhost:7357/assets/vendor.js:163380:34)
 at Class._modelFor (http://localhost:7357/assets/vendor.js:163351:31)
 at Class.modelFor (http://localhost:7357/assets/vendor.js:163344:19)
 at Class.createRecord (http://localhost:7357/assets/vendor.js:161778:29)
 at Backburner.run (http://localhost:7357/assets/vendor.js:15676:23)
 at Object.run (http://localhost:7357/assets/vendor.js:37202:27) at http://localhost:7357/assets/tests.js:322:44
 at Array.forEach (native) at Object.<anonymous> (http://localhost:7357/assets/tests.js:310:12)
```

```
Ember.VERSION = 2.11.2
DS.VERSION = 2.11.2
```

Reproduceable with Ember beta: https://ember-twiddle.com/5b838a44e2a4ea0040cd80518019a466?openFiles=tests.integration.components.my-component-test.js%2C

**Comment by ming-codes** [comment]
2.11.1 has no issue though.

**Comment by ming-codes** [comment]
Fixed in 2.11.3

**Comment by snewcomer** [comment]
@ming-code Seeing this on 2.12.0

**Comment by stefanpenner** [comment]
@snewcomer can you share a stack-trace or reproduction?

**Comment by rwjblue** [comment]
Please open a new issue with stack / repro instructions. The original issue reported here was fixed, there definitely may be more cases that need to be addressed, but that should be tracked as a separate issue.
