### ISSUE TITLE
2.14 beta has issues with deprecating

### ISSUE THREAD

**Issue by kellyselden** [emberjs/data#4983]
I started seeing this in Travis today:

```
text: '\'TypeError: Cannot read property \\\'apply\\\' of undefined\\n    at deprecate 
(http://localhost:7357/assets/vendor.js:80685:36)\\n    at warnForDeprecatedInitializers 
(http://localhost:7357/assets/vendor.js:82996:26)\\n    at deprecateOldEmberDataInitializers 
(http://localhost:7357/assets/vendor.js:82986:9)\\n    at Object.initializeStoreService [as initialize] 
(http://localhost:7357/assets/vendor.js:82965:5)\\n    at http://localhost:7357/assets/vendor.js:22805:21\\n  
  at Vertices.each (http://localhost:7357/assets/vendor.js:21440:17)\\n    at Vertices.walk 
(http://localhost:7357/assets/vendor.js:21369:18)\\n    at DAG.each 
(http://localhost:7357/assets/vendor.js:21314:28)\\n    at DAG.topsort 
(http://localhost:7357/assets/vendor.js:21320:18)\\n    at Class._runInitializer 
(http://localhost:7357/assets/vendor.js:22819:13)\'\n' }
```

https://travis-ci.org/kellyselden/ember-data-fetch-support/jobs/231285589#L1507
https://travis-ci.org/kellyselden/ember-tree/jobs/231350240#L1634

**Comment by rwjblue** [comment]
I think this was actually an Ember issue, and I fixed it in https://github.com/emberjs/ember.js/pull/15239.  Happy to reopen if I am wrong...
