### ISSUE TITLE
Error: Cannot find module 'babel-plugin-transform-es2015-block-scoping'

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#5080]
with `npm@2` which is the default in Node 4 which is recommended to be used by Ember addons at the moment:

```
Error: Cannot find module 'babel-plugin-transform-es2015-block-scoping'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/simplabs/ember-cli-pixijs/node_modules/ember-data/lib/stripped-build-plugins.js:7:29)
```

see https://github.com/emberjs/data/blob/v2.14.5/lib/stripped-build-plugins.js#L7

tl;dr if you want to `require()` something then it should be a dependency of your project

This is a duplicate of https://github.com/emberjs/data/issues/5024 since I can't reopen the original issue and this problem is apparently not resolved even though the original issue was closed for some reason.

**Comment by Turbo87** [comment]
Resolved by https://github.com/emberjs/data/pull/5081
