### ISSUE TITLE
2.14.6 - Error loading relationships in templates You modified "X" twice

### ISSUE THREAD

**Issue by urbany** [emberjs/data#5082]
Hi, i just upgraded from: 2.13.2 to 2.14.6.

And now some templates where I was successfully doing:

`{{ car.category }}`

Where car is a model which has a category defined like: `category: belongsTo()`

Throws an error:
```
Assertion Failed: You modified "category" twice on <my-project@model:car::ember1007:1011> in a single render. It was rendered in "component:table-row" and modified in "component:table-row". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
at Object.assert (/assets/vendor.js:29556:15)
    at Object.exports.assertNotRendered (/assets/vendor.js:39055:42)
    at propertyDidChange (/assets/vendor.js:39172:15)
    at Class.propertyDidChange (/assets/vendor.js:55148:41)
    at Class.notifyPropertyChange (/assets/vendor.js:55163:12)
    at InternalModel.notifyPropertyChange (/assets/vendor.js:216173:20)
    at BelongsToRelationship.updateLink (/assets/vendor.js:213058:24)
    at BelongsToRelationship.push (/assets/vendor.js:213137:14)
    at Relationships.get (/assets/vendor.js:214144:22)
    at Class.get (/assets/vendor.js:221824:49)
```

If i add `{{debugger}}` before that line in the template and try in the console `get('car.category')` I get the same error, but the second time it works correctly, can this be something to the new lazily load of relationships?

**Comment by kumkanillam** [comment]
I am not sure, but this may be related to https://github.com/emberjs/data/issues/4942

**Comment by urbany** [comment]
@kumkanillam thank you very much!
It's the same bug, so I'm gonna close this and follow that issue.
