### ISSUE TITLE
Cannot read property 'store' of undefined only in production on 3.0.1

### ISSUE THREAD

**Issue by scottkidder** [emberjs/data#5355]
Getting a strange error only in production builds after upgrade to ember-source 3.0.0 and ember-data 3.0.1

```
VM4624 vendor-f6c636b11c48d8c28119b54f2736e406.js:3725 Error while processing route: signin Cannot read property 'store' of undefined TypeError: Cannot read property 'store' of undefined
    at Object.Te [as set] (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:3293:10)
    at o.adapterFor (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:13218:51)
    at o.queryRecord (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:13161:60)
    at o.model (http://localhost:4200/b/assets/brokermate-0bec548f9e372a3b156bdfd6c5e7ae92.js:496:2561)
    at o.deserialize (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:3627:121)
    at http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:4400:88
    at n.e.runSharedModelHook (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:4400:122)
    at n.getModel (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:4420:13)
    at x (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:4527:25)
    at S (http://localhost:4200/b/assets/vendor-f6c636b11c48d8c28119b54f2736e406.js:4535:9)
```

**Comment by Bartheleway** [comment]
Are you trying to read the store object using `this.store` or using `this.get('store')` ? While doing some test I found that this could give different results.

**Comment by runspired** [comment]
Unfortunately there's not enough info here to reproduce or debug this; however, I suspect you are dealing with some object that you have destroyed.
