### ISSUE TITLE
ember-data@3.6.0: circular dependency 

### ISSUE THREAD

**Issue by nfc036** [emberjs/data#5799]
With ember-data@3.6.0 I get a "circular dependency"-Warning/Error in console when running "ember serve".

```
Circular dependency: ..\..\..\..\Users\username\TEMP\broccoli-9436umqGtnnqeeVy\cache-200-rollup\build\-private\system\model\model.js -> ..\..\..\..\Users\username\TEMP\broccoli-9436umqGtnnqeeVy\cache-200-rollup\build\-private\system\model\internal-model.js -> ..\..\..\..\Users\username\TEMP\broccoli-9436umqGtnnqeeVy\cache-200-rollup\build\-private\system\references.js -> ..\..\..\..\Users\username\TEMP\broccoli-9436umqGtnnqeeVy\cache-200-rollup\build\-private\system\references\belongs-to.js -> ..\..\..\..\Users\username\TEMP\broccoli-9436umqGtnnqeeVy\cache-200-rollup\build\-private\system\model\model.js
```
Without temporary directories the circular reference is: 
```
-private\system\model\model.js ->
-private\system\model\internal-model.js ->
-private\system\references.js ->
-private\system\references\belongs-to.js ->
-private\system\model\model.js 
```

Beside this, the process starts normally. However, the message is irritating.

I'm working on windows with ember-cli@3.5.1. ember-data@3.5.2 does not show this behavior.

**Comment by vishnu-arecabay** [comment]
I'm facing a similar issue an exact similar issue as well,
`../../../../../../var/folders/gp/51prsfcx5gd_cvhxzd6jfl7w0000gn/T/broccoli-6168O1WB8SRcakja/cache-159-rollup/build/-private/system/model/model.js ->

../../../../../../var/folders/gp/51prsfcx5gd_cvhxzd6jfl7w0000gn/T/broccoli-6168O1WB8SRcakja/cache-159-rollup/build/-private/system/model/internal-model.js ->

../../../../../../var/folders/gp/51prsfcx5gd_cvhxzd6jfl7w0000gn/T/broccoli-6168O1WB8SRcakja/cache-159-rollup/build/-private/system/references.js ->

../../../../../../var/folders/gp/51prsfcx5gd_cvhxzd6jfl7w0000gn/T/broccoli-6168O1WB8SRcakja/cache-159-rollup/build/-private/system/references/belongs-to.js ->

../../../../../../var/folders/gp/51prsfcx5gd_cvhxzd6jfl7w0000gn/T/broccoli-6168O1WB8SRcakja/cache-159-rollup/build/-private/system/model/model.js`

**Comment by runspired** [comment]
This warning printed here is noisy but not problematic. We will try to silence it going forward, but it is the unfortunate artifact of how importing classes for `Typescript` conflicts with `rollup`'s circular dependency import checks.

**Comment by ryanto** [comment]
Seeing this as well on a new Ember 3.6 app. No issues with Ember Data's functionality, only issue is the warning message!

**Comment by rinoldsimon** [comment]
seeing similar issue when i run `ember serve`
`ember-cli` - `3.7.1`
`ember-data` - `3.7.0`
`ember-cli-babel` - `7.4.0`
```
Circular dependency: ../../../../../var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/broccoli-131479udYxjAGQvZQ/cache-229-rollup/build/-private/system/model/model.js -> ../../../../../var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/broccoli-131479udYxjAGQvZQ/cache-229-rollup/build/-private/system/model/internal-model.js -> ../../../../../var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/broccoli-131479udYxjAGQvZQ/cache-229-rollup/build/-private/system/references.js -> ../../../../../var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/broccoli-131479udYxjAGQvZQ/cache-229-rollup/build/-private/system/references/belongs-to.js -> ../../../../../var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/broccoli-131479udYxjAGQvZQ/cache-229-rollup/build/-private/system/model/model.js
Build Error (broccoli-persistent-filter:Babel > [Babel: medzbook-client]) in medzbook-client/adapters/application.js

[BABEL] /Users/rinold/mb_project/workspace/web_client/medzbook-client/adapters/application.js: Invalid Option: compact is not a valid top-level option.
        Maybe you meant to use 'spec'? (While processing: "/Users/rinold/mb_project/workspace/web_client/node_modules/@babel/preset-env/lib/index.js")


Stack Trace and Error Report: /var/folders/5l/n69gw2bx779gl145qqxyq17c0000gp/T/error.dump.7477b08fd939ca44312846ff8e2c93f8.log
file changed adapters/application.js
```

**Comment by mansona** [comment]
@rinoldsimon it looks like you do have the same warning but it is a different issue that is breaking your build 🤔 I think you should open a new issue (potentially on the ember-cli repo) or ask for some help in #help on the Ember Community Discord 👍

**Comment by Redsandro** [comment]
Same issue.

```
system/model/model.js ->
system/model/internal-model.js -> 
system/references.js -> 
system/references/belongs-to.js -> 
system/model/model.js
```

I've been trying to get rid of it by commenting out more and more code, thinking this caused fastboot not to work. But I guess that's a totally different issue.

**Comment by runspired** [comment]
@Redsandro this is not an error and is a misguided warning that we've silenced in more recent builds and releases

**Comment by Redsandro** [comment]
@runspired thank you for clarifying.

Meanwhile, I figured out what the problem with FastBoot was. It was an unclear error message. Now isn't that ironic? :robot: 

https://github.com/ember-fastboot/ember-cli-fastboot/issues/622

(The issue that google suggested was even created by myself last year. Ironiception! :fireworks: )

**Comment by BryanCrotaz** [comment]
This is causing my test run to fail in CI:

```
export PATH=$PATH:node_modules/.bin
  ember test --silent -R xunit > ./test-results/results.xml
  shell: /usr/bin/bash -e {0}
  env:
    CI: true
    BROCCOLI_ENV: test
    HOST_KEY_BITBUCKET: ***
    NPM_AUTH_TOKEN: ***
    SSH_AUTH_SOCK: /tmp/ssh-KnGfOAS9pua6/agent.1750
    SSH_AGENT_PID: 1751
Circular dependency: ../../../../../tmp/broccoli-182[3](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:3)iBtGIhvR6NRI/cache-[4](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:4)49-rollup/build/-private/system/model/model.js -> ../../../../../tmp/broccoli-1823iBtGIhvR6NRI/cache-449-rollup/build/-private/system/model/internal-model.js -> ../../../../../tmp/broccoli-1823iBtGIhvR6NRI/cache-449-rollup/build/-private/system/references.js -> ../../../../../tmp/broccoli-1823iBtGIhvR6NRI/cache-449-rollup/build/-private/system/references/belongs-to.js -> ../../../../../tmp/broccoli-1823iBtGIhvR6NRI/cache-449-rollup/build/-private/system/model/model.js
Typechecking failed

=================================================================================

ENV Summary:

  TIME: Sat Mar 0[5](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:5) 2022 22:14:39 GMT+0000 (Coordinated Universal Time)
  TITLE: ember
  ARGV:
  - /opt/hostedtoolcache/node/12.22.10/x[6](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:6)4/bin/node
  - /home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/.bin/ember
  - test
  - --silent
  - -R
  - xunit
  EXEC_PATH: /opt/hostedtoolcache/node/12.22.10/x64/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /opt/hostedtoolcache/node/12.22.10/x64/bin
  - /home/linuxbrew/.linuxbrew/bin
  - /home/linuxbrew/.linuxbrew/sbin
  - /home/runner/.local/bin
  - /opt/pipx_bin
  - /home/runner/.cargo/bin
  - /home/runner/.config/composer/vendor/bin
  - /usr/local/.ghcup/bin
  - /home/runner/.dotnet/tools
  - /snap/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - node_modules/.bin
  PLATFORM: linux x64
  FREEMEM: 1539600384
  TOTALMEM: [7](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:7)2[8](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:8)4850688
  UPTIME: 283
  LOADAVG: 1.[9](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:9)1,0.95,0.38
  CPUS:
  - Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz - 2095
  - Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz - 2095
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 37.0
  - http_parser: 2.9.4
  - icu: 67.1
  - llhttp: 2.1.4
  - modules: 72
  - napi: 8
  - nghttp2: 1.41.0
  - node: 12.22.[10](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:10)
  - openssl: 1.1.1m
  - tz: 2021a4
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 7.8.279.23-node.56
  - zlib: 1.2.[11](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:11)

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Typechecking failed
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Typechecking failed
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Typechecking failed
    at Class.postBuild (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli-typescript/js/addon.js:73:19)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function.all (<anonymous>:null:null)
    at Builder.build (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/models/builder.js:209:7)
    at BuildTask.run (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/tasks/build.js:32:21)
    at Class.run (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/commands/test.js:197:7)
    at /home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/cli/cli.js:204:32
    at CLI.run (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/cli/cli.js:251:[14](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:14))
    at module.exports (/home/runner/work/pixelpipe-ember-playback-core/pixelpipe-ember-playback-core/node_modules/ember-cli/lib/cli/index.js:1[45](https://github.com/silver-curve/pixelpipe-ember-playback-core/runs/5435239600?check_suite_focus=true#step:10:45):12)


=================================================================================

Error: Process completed with exit code 1.
```
