### ISSUE TITLE
ember-data@3.6.0 queryParam type array

### ISSUE THREAD

**Issue by arnoschneid** [emberjs/data#5800]
If I try to use a queryParam of type array I got:

```cli
router.js:1070 Error while processing route: admin.users Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
    at ComputedProperty.get (http://localhost:4200/assets/vendor.js:27101:12)
    at Array.CPGETTER_FUNCTION [as []] (http://localhost:4200/assets/vendor.js:25507:31)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5185:17)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
    at Function.jQuery.extend.jQuery.fn.extend (http://localhost:4200/assets/vendor.js:5206:30)
```
With Ember 3.5.0 all worked fine.

### Reproduction

Controller:
`queryParams: ['filter'],`
`filter: A(),`

Route:
`model(params) {`
`  return this.store.query('record', params);`
`}`

### Versions
```cli
ember-source@3.6.0
ember-cli@3.6.0
ember-data@3.6.0
```

**Comment by nfc036** [comment]
Isn't this a problem of ember-source@3.6.0!? Probably unrelated to ember-data. See https://github.com/emberjs/ember.js/issues/17190

**Comment by arnoschneid** [comment]
Yes, this is not ember-data related. Thanks for your hint and the fast response.
