### ISSUE TITLE
_fetchRequest not returning a promise in Octane blueprint

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/data#5918]
### Reproduction

GitHub repo with minimal reproduction: https://github.com/CodingItWrong/octane-sandbox

### Description

Expected behavior: `this.store.findAll('widget')` should attempt to make an HTTP request
Actual behavior: `this.store.findAll('widget')` results in the following error:

```
Error while processing route: index Cannot read property 'catch' of undefined TypeError: Cannot read property 'catch' of undefined
    at Class.ajax (http://localhost:4200/assets/vendor.js:79199:40)
    at Class.findAll (http://localhost:4200/assets/vendor.js:78775:19)
    at Ember.RSVP.Promise.resolve.then (http://localhost:4200/assets/vendor.js:70555:67)
    at tryCatcher (http://localhost:4200/assets/vendor.js:57834:21)
    at invokeCallback (http://localhost:4200/assets/vendor.js:58005:33)
    at config.async (http://localhost:4200/assets/vendor.js:58069:26)
    at _runloop.backburner.schedule (http://localhost:4200/assets/vendor.js:52520:53)
    at invoke (http://localhost:4200/assets/vendor.js:50837:16)
    at Queue.flush (http://localhost:4200/assets/vendor.js:50728:13)
    at DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:50925:21)
```

The line throwing the error is highlighted below:

```javascript
ajax(url, type, options) {
  var adapter = this;
  var requestData = {
    url: url,
    method: type
  };
  var hash = adapter.ajaxOptions(url, type, options);

  if (Ember.get(this, 'useFetch')) {
    // BELOW IS THE LINE
    return this._fetchRequest(hash).catch(() => {}).then(response => {
      return Ember.RSVP.hash({
        response,
        payload: (0, _determineBodyPromise.default)(response, requestData)
      });
    }).then(({
      response,
      payload
    }) => {
      if (response.ok) {
        return fetchSuccessHandler(adapter, payload, response, requestData);
      } else {
        throw fetchErrorHandler(adapter, payload, response, null, requestData);
      }
    });
  }
```

Changing to Ember Data release 3.8.0 and enabling @ember/jquery fixes the problem.

### Versions

```cli
octane-sandbox@0.0.0 /Users/josh/apps/temp/octane-sandbox
└── ember-source@3.10.0-canary

octane-sandbox@0.0.0 /Users/josh/apps/temp/octane-sandbox
└── ember-cli@3.9.0-beta.2  (github:ember-cli/ember-cli#185c0773f383631f4608fa06aa782e10e68a724d)

octane-sandbox@0.0.0 /Users/josh/apps/temp/octane-sandbox
└── ember-data@3.9.0-canary  (github:emberjs/data#722da7ce75597735f1769a98875fcadccb4b8749)
```

**Comment by wagenet** [comment]
I can confirm this.
