### ISSUE TITLE
Cannot update ember-data using yarn

### ISSUE THREAD

**Issue by baron1405** [emberjs/data#6273]
Attempting to upgrade ember-data from 3.10.0 to 3.11.2, I get the following error:
```
yarn upgrade v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
yarn upgrade v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Couldn't find package "@ember-data/-build-infra" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:50647:15)
    at Generator.next (<anonymous>)
    at step (/home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:304:30)
    at /home/baron/projects/apron-ui/node_modules/yarn/lib/cli.js:315:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
All other ember packages (e.g. ember-cli, ember-source) update successfully. I have verified that the package is listed in the npm registry. I have tried removing my yarn.lock and node_modules directory to start fresh but the problem still occurs.

Environment:
CentOS 7.6
Yarn 1.17.3

**Comment by runspired** [comment]
@baron1405,

This likely means you are using a custom registry and that registry needs to import the new packages that `ember-data` depends upon.

You can see that the `-build-infra` package is indeed published correctly by using `npm view @ember-data/-build-infra`

<img width="934" alt="Screen Shot 2019-07-23 at 9 13 04 AM" src="https://user-images.githubusercontent.com/650309/61728461-1d1a3800-ad2a-11e9-9cd3-a15afe42deb4.png">

**Comment by baron1405** [comment]
Apparently others have hit this as well - verdaccio#1429.

**Comment by baron1405** [comment]
Talking directly to the yarn or npm repos works so it must be something related to the npm plugin for Nexus 2.
