### ISSUE TITLE
Cannot find module '@babel/plugin-transform-block-scoping'

### ISSUE THREAD

**Issue by jelhan** [emberjs/data#6421]
Ember Data requires `@babel/plugin-transform-block-scoping` in `packages/-build-infra/src/stripped-build-plugins.js` but it's not listed as a dependency in [`package.json`](https://github.com/emberjs/data/tree/master/packages/-build-infra): https://github.com/emberjs/data/blob/4b7838fe81571468d2ae84d6743ac42b2c1f118a/packages/-build-infra/src/stripped-build-plugins.js#L9

In some scenarios the resolution seems to fail even so the package exists accordingly to yarn:

```
$ yarn why @babel/plugin-transform-block-scoping
yarn why v1.17.3
[1/4] Why do we have the module "@babel/plugin-transform-block-scoping"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@babel/plugin-transform-block-scoping@7.6.0"
info Reasons this module exists
   - "ember-cli-babel#@babel#preset-env" depends on it
   - Hoisted from "ember-cli-babel#@babel#preset-env#@babel#plugin-transform-block-scoping"
Done in 1.14s.
```

I wasn't able to provide a simple reproduction yet. :cry: 

This seems to be a regression of #5080.

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: MODULE_NOT_FOUND
  - codeFrame: [undefined]
  - errorMessage: Cannot find module '@babel/plugin-transform-block-scoping'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module '@babel/plugin-transform-block-scoping'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module '@babel/plugin-transform-block-scoping'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/home/main/Code/fey/pruefung-client/node_modules/@ember-data/-build-infra/src/stripped-build-plugins.js:9:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by runspired** [comment]
Resolved on master, likely needs a fix for beta/release. @Gaurav0 think you could grab this?

**Comment by Gaurav0** [comment]
@runspired sure.

I didn't know if it was really a problem, I included that in dependencies to satisfy eslint v6, lol.

**Comment by runspired** [comment]
Fix has been backported to both beta and release

**Comment by jelhan** [comment]
Thanks a lot for the quick response! :clap:
