### ISSUE TITLE
Fastboot test run throws deprecations

### ISSUE THREAD

**Issue by igorT** [emberjs/data#6680]
```
  DEPRECATION: The <fastboot-test-app@adapter:application::ember174>#fastboot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
        at logDeprecationStackTrace (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:106:1)
        at HANDLERS.(anonymous function) (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at raiseOnDeprecation (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:133:1)
        at HANDLERS.(anonymous function) (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at invoke (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:38:1)
        at deprecate (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:171:1)
        at ComputedProperty.clobberSet (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:3396:1)
        at ComputedProperty.set (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:3362:1)
        at initialize (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/system/core_object.js:68:1)
        at Function.create (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/system/core_object.js:681:1)
        at FactoryManager.create (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:552:1)
        at instantiateFactory (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:367:1)
        at lookup (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:290:1)
        at Container.lookup (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:134:1)
        at Class.lookup (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:81:1)
        at Store.adapterFor (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:15154:1)
        at Store._fetchAll (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:14222:1)
        at Store.findAll (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:14208:1)
        at IndexRoute.model (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/fastboot-test-app.js:525:25)
        at IndexRoute.deserialize (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:1040:1)
        at UnresolvedRouteInfoByParam.getModel (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/router_js.js:895:1)
        at _rsvp.Promise.resolve.then.then.then.then (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/router_js.js:691:1)
        at invokeCallback (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/rsvp.js:493:1)
        at publish (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/rsvp.js:476:1)
        at _runloop.backburner.schedule (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/ember-testing/lib/ext/rsvp.js:19:1)
        at invokeWithOnError (/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/broccoli-11489a1QZBnuWWstu/out-260-append_ember_auto_import_analyzer/assets/backburner.js:347:1)
```

**Comment by Gaurav0** [comment]
This seems to come from ember-cli-fastboot-testing. Reported here: https://github.com/embermap/ember-cli-fastboot-testing/issues/198

**Comment by Gaurav0** [comment]
There is another deprecation being thrown that is coming from ember-simple-tree, reported here: https://github.com/btecu/ember-simple-tree/issues/30

**Comment by runspired** [comment]
> Edit: I think we shouldn't be creating a computed property named fastboot in the future, it is expected to be an injected service

We can't use the injected service because that would force users to use fastboot.

**Comment by Gaurav0** [comment]
@runspired I understand, just saying we shouldn't call our computed property 'fastboot', because it gets overriidden in fastboot....
