### ISSUE TITLE
3.12+ are missing a dependency on @ember/string

### ISSUE THREAD

**Issue by samselikoff** [emberjs/data#6791]
Ember CLI Mirage's builds started failing, under the Floating Deps scenario. I tracked it down to Ember Data in my lockfile; when I removed it and regenerated yarn.lock, it brought in 3.8.1 as a transitive dep of AddonDocs.

The specific error was 

> Error: Could not find module `@ember/string` imported from `ember-resolver/resolvers/classic/index`

<details>
  <summary>Full stack</summary>
  
```
Error: Could not find module `@ember/string` imported from `ember-resolver/resolvers/classic/index`
    at missingModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:247:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:258:1)
    at Module.findDeps (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:168:1)
    at findModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:262:1)
    at Object.requireModule (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/dist/assets/vendor/loader/loader.js:24:1)
    at Object.<anonymous> (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/ember-app.js:213:18)
    at VMSandbox.run (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/ember-app.js:212:30)
    at EmberApp.retrieveSandboxedApp (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/ember-app.js:237:17)
    at new EmberApp (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/samselikoff/Projects/oss/ember-cli-mirage/node_modules/fastboot/src/index.js:52:10)
    at Object.<anonymous> (/Users/samselikoff/Projects/oss/ember-cli-mirage/test-projects/01-basic-app/fastboot-tests/included-files-test.js:21:20)
```
</details>

**Comment by runspired** [comment]
This appears to be an issue with ember resolver. @ember/string comes from ember-source back then (May still?)

**Comment by runspired** [comment]
I believe the issue here is that `ember-resolver` does not specify `@ember/string` as a dep while `ember-data` (correctly) does.

https://github.com/ember-cli/ember-resolver/blob/master/package.json#L26

Likely the issue here is that `@ember/string` was previously hoisted in the dep tree where ember-resolver could find it, but due to other dependency bumps no longer is. Pinning ember-data via resolutions is forcing the hoist.

**Comment by runspired** [comment]
cc @rwjblue for the resolver issue.

**Comment by runspired** [comment]
After digging in more, 3.8.1 is doing the right thing, it just unfortunately results in ember-resolver not having the package due to hoisting not occurring for ember-cli-mirage.

Using resolutions could be helping to resolve this issue, but it is more likely that this doesn't fail in 3.12+ due to a bug in EmberData in those versions whereby we ourselves forgot to keep this dependency in our dependencies.

**Comment by Gaurav0** [comment]
Am I missing something? @ember/string still seems to exist in ember-source and is not a "real" package. The `@ember/string` package seems to be not up to date with the one in `ember-source`. Therefore including '@ember/string` as an explicit dependency rather than an implicit peerDependency on `ember-source` in addons is likely to break any other addon that does not explicitly depend on the `@ember/string` package, and possibly break apps that depend on having the correct version of `@ember/string` files in lockstep with `ember-source` ?

I think the correct thing to do is to drop the explicit dependency from `ember-data` 3.8 lts branch and republish. @rwjblue ?

**Comment by runspired** [comment]
@Gaurav0 we refactored to add the dep because not having it was being deprecated. Perhaps the @ember/string deprecation got left in a bad state?

**Comment by igorT** [comment]
@rwjblue is investigating

**Comment by mjuniper** [comment]
I've run into this issue when upgrading our app to 3.12. It is not clear to me from the above how to resolve it. Can somebody please point me in the right direction?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by igorT** [comment]
We haven't run into this again, @mjuniper I hope this isn't an issue anymore, I don't think we have had more reports. @rwjblue can you confirm this can be closed? I'll add it to our next meeting agend. @sandstrom thanks a bunch for the gardening!

**Comment by sandstrom** [comment]
@igorT No problem. Btw, have you thought about registering as a Github Sponsor? 😄

**Comment by igorT** [comment]
@sandstrom I believe we are covered under the ember.js umbrella

**Comment by sandstrom** [comment]
Yes, Ember as an open-source org has already signed up, but there is also the option of signing up individually. Could be for contributions outside Ember, or if someone wanted to channel money to a specific Ember contributor, for example someone working on Ember Data.

**Comment by hjdivad** [comment]
The issue is that https://github.com/babel/ember-cli-babel/pull/265/commits needs to be backported to ember-cli-babel@6.

The @ember/string detection in ember-cli-babel@6 is wrong.  Until the fix is backported you'll see these errors when

1. any build-time dependency includes `@ember/string` (c.f. `yarn why @ember/string`)
2. the runtime does not include `@ember/string`

This can happen  if you have two versions of ember-data at build time, and the one at runtime does not have the `@ember/string` dependency.
