### ISSUE TITLE
Performance tests on PRs are failing, but showing as successful

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#7403]
```
TypeError: InitialRenderBenchmark is not a constructor
    at /home/runner/work/data/data/bin/relationship-performance-tracking/src/tracerbench.js:121:23
    at Object.<anonymous> (/home/runner/work/data/data/bin/relationship-performance-tracking/src/tracerbench.js:149:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by igorT** [comment]
Thanks for the report, taking a look.
