### ISSUE TITLE
AdapterError triggers @ember/error deprecation

### ISSUE THREAD

**Issue by sebastianhelbig** [emberjs/data#8404]
```cli
ember-data 4.9.1
ember-source 4.10.0

Error: The @ember/error package merely re-exported the native Error and is deprecated. Please use a native Error directly instead.
    at handleDeprecationWorkflow (main.js:41:1)
    at HANDLERS.<computed> (handlers.js:9:7)
    at deprecationCollector (main.js:78:1)
    at HANDLERS.<computed> (handlers.js:9:7)
    at setup-context.js:32:1
    at HANDLERS.<computed> (handlers.js:9:7)
    at invoke (handlers.js:18:7)
    at deprecate (deprecate.js:188:11)
    at AdapterError.EmberDebugConstructor (index.js:17:14)
    at new AdapterError (error.js:84:1)
```

**Comment by runspired** [comment]
resolved by #8422 and #8412
