### ISSUE TITLE
Installing ember-data independently: build fails

### ISSUE THREAD

**Issue by CarstenRuetz** [emberjs/data#8584]
Hi team,  

after reading the docs on emberData, I wanted to give it a spin: 
I want to use emberData independently of an ember project, but the build fails: 

### Reproduction
git clone https://github.com/CarstenRuetz/emberdata-test
cd emberdata-test 
npm run dev 

expectation: build works 
situation: build fails with 

```
3:06:04 PM [vite] Internal server error: Failed to resolve entry for package "@ember-data/store". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /media/carsten/data/Documents/temple/test/test2/resources/js/App.vue
      at packageEntryFailure (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:23384:11)
      at resolvePackageEntry (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:23381:5)
      at tryNodeResolve (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:23115:20)
      at Context.resolveId (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:22876:28)
      at async Object.resolveId (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:42805:32)
      at async TransformContext.resolve (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:42533:23)
      at async normalizeUrl (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:40501:34)
      at async file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:40652:47
      at async Promise.all (index 0)
      at async TransformContext.transform (file:///media/carsten/data/Documents/temple/test/test2/node_modules/vite/dist/node/chunks/dep-a178814b.js:40578:13)
```

### Description
I have been following the docs here: https://github.com/emberjs/data/tree/main/packages/store

In emberdata-test/resources/js/App.vue I want to create a store like this: 

```
import Store from "@ember-data/store";
import Cache from "@ember-data/json-api";

class EmberStore extends Store {
    createCache(storeWrapper) {
        return new Cache(storeWrapper);
    }
}

```

This results in the above shown error.

I did see, that on the roadmap there were some comments about making emberData generally more independent of ember. The Docs for emberData also seem formulated in a way that suggest this can be used independently of ember. Is this correct?

Any help would be appreciated!

### Versions

Run the following command and paste the output below: `pnpm list ember-source && pnpm list ember-cli && pnpm list --pattern ember-data`.

I ran npm list instead: 

```
$ npm list
emberdata-test@ /media/carsten/data/Documents/temple/emberdata-test
├── @vitejs/plugin-vue@4.2.1
├── axios@1.4.0
├── ember-data@4.12.0
├── laravel-vite-plugin@0.7.4
├── vite@4.3.3
└── vue@3.2.47
```

**Comment by runspired** [comment]
We are not yet independent but are getting there pretty rapidly, goal is for 6.0 to be independent.

**Comment by runspired** [comment]
Going to close this, but please keep in touch we are eager for folks to help/test our independence from Ember itself
