### ISSUE TITLE
Error `Could not find module `@warp-drive/core-types/request` imported from `(require)`` after update to 5.3.1

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#9239]
In my app i'm getting this error after updating from 5.3.0 to 5.3.1:

![grafik](https://github.com/emberjs/data/assets/19845290/281e6992-3a08-480b-8ceb-a67a7dfbaa2f)

I have seen in last days that also in ember-power-select i have got a error while bump (havn't got time yet do check why it occures)
https://github.com/cibernox/ember-power-select/actions/runs/8048924871/job/21981274139?pr=1706

Is there anything braking which was not documented?

Enviroment:
Ember Data: 5.3.1
Ember Source: 5.4.0
NodeJs: 18.19.1
NPM: 10.2.4

Installed ember-data packages:
```
   "@ember-data/adapter": "~5.3.1",
    "@ember-data/debug": "~5.3.1",
    "@ember-data/graph": "~5.3.1",
    "@ember-data/json-api": "~5.3.1",
    "@ember-data/legacy-compat": "~5.3.1",
    "@ember-data/model": "~5.3.1",
    "@ember-data/request": "~5.3.1",
    "@ember-data/serializer": "~5.3.1",
    "@ember-data/store": "~5.3.1",
    "@ember-data/tracking": "~5.3.1",
```

**Comment by Jopie01** [comment]
I walked into this issue as well and added `"@warp-drive/core-types": "0.0.0-alpha.8"` to my `package.json` and did a `pnpm install` and everything started to work again.

Seems like there is a dependency missing somewhere.

**Comment by runspired** [comment]
core-types was incorrectly left as a peer-dep when we stripped types for publishing, will be publishing a 5.3.2

You only hit this if you have configured your package manager to not auto-install peers, kudos for having done so!

**Comment by runspired** [comment]
fixed in 5.3.2 https://github.com/emberjs/data/releases/tag/v5.3.2

**Comment by olyckne** [comment]
Updated to 5.3.1 yesterday without any issues.
But now when I'm updating to 5.3.2 I am getting this exact issue...

Had a hard time updating at first. Had to first remove ember-cli-mirage to get rid of dependency conflicts.
Then `npm upgrade ember-data @ember-data/store @ember-data/json-api` only updates `ember-data` but only `npm upgrade ember-data` fails due to peer dependency conflicts 

So after running the following I am where I want to be:
```bash
npm remove ember-cli-mirage
npm upgrade ember-data @ember-data/store @ember-data/json-api
npm upgrade @ember-data/store @ember-data/json-api
npm i -D ember-cli-mirage
```

but then I'm getting this error.

Not sure how to debug this.

Enviroment:
Ember Data: 5.3.2
Ember Source: 5.6.0
NodeJs: 20.11.1
NPM: 10.4.0

Installed ember-data packages:
```
"@ember-data/json-api": "^5.3.2",
"@ember-data/store": "^5.3.2",
"ember-data": "^5.3.2"
```

Tried to remove `@ember-data/json-api` and `@ember-data/store` so I just have `ember-data` but still getting the same error.

Tried to install all packages I actually use in the application `npm I -D @ember-data/json-api @ember-data/store @ember-data/adapter @ember-data/model @ember-data/serializer @ember-data/request` with no success

**Comment by runspired** [comment]
@olyckne could you paste a trace? curious which package claims it needs it

**Comment by olyckne** [comment]
@runspired 

This is what I get

Maybe it doesn't help but we are slowly activating more Embroider and currently having these two enabled:
```
staticAddonTestSupportTrees: true,
staticAddonTrees: true,
```

```
loader.js:247 Uncaught Error: Could not find module `@warp-drive/core-types/request` imported from `(require)`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at requireModule (loader.js:24:1)
    at eval (?../../@embroider/babel-loader-9/index.js?%7B%22variant%22:%7B%22name%22:%22dev%22,%22runtime%22:%22browser%22,%22optimizeForProduction%22:false%7D,%22appBabelConfigPath%22:%22/Users/mattiaslyckne/Code/glesys/cloud/client/node_modules/.embroider/rewritten-app/_babel_config_.js%22,%22cacheDirectory%22:%22/private/var/folders/1p/ymk34w294wb63nnmfb5ygk0c0000gn/T/embroider/webpack-babel-loader%22%7D!../../@embroider/webpack/src/virtual-loader.js?f=%252F%2540embroider%252Fext-cjs%252F%2540warp-drive%252Fcore-types%252Frequest&a=%252FUsers%252Fmattiaslyckne%252FCode%252Fglesys%252Fcloud%252Fclient:1:18)
    at ../../@embroider/babel-loader-9/index.js?{"variant":{"name":"dev","runtime":"browser","optimizeForProduction":false},"appBabelConfigPath":"/Users/mattiaslyckne/Code/glesys/cloud/client/node_modules/.embroider/rewritten-app/_babel_config_.js","cacheDirectory":"/private/var/folders/1p/ymk34w294wb63nnmfb5ygk0c0000gn/T/embroider/webpack-babel-loader"}!../../@embroider/webpack/src/virtual-loader.js?f=%2F%40embroider%2Fext-cjs%2F%40warp-drive%2Fcore-types%2Frequest&a=%2FUsers%2Fmattiaslyckne%2FCode%2Fglesys%2Fcloud%2Fclient! (chunk.831ba69f90e4e0dcfcb6.js:407:1)
    at __webpack_require__ (chunk.3cfb315365df1011084b.js:31:42)
    at eval (cache-handler-XLbbNJdo.js:33:88)
    at ../rewritten-packages/@ember-data/store.56db784d/node_modules/@ember-data/store/cache-handler-XLbbNJdo.js (chunk.514b3296aa8fe961418a.js:11590:1)
    at __webpack_require__ (chunk.3cfb315365df1011084b.js:31:42)
    at eval (-private.js:30:81)
missingModule @ loader.js:247
findModule @ loader.js:258
requireModule @ loader.js:24
eval @ ?../../@embroider/babel-loader-9/index.js?%7B%22variant%22:%7B%22name%22:%22dev%22,%22runtime%22:%22browser%22,%22optimizeForProduction%22:false%7D,%22appBabelConfigPath%22:%22/Users/mattiaslyckne/Code/glesys/cloud/client/node_modules/.embroider/rewritten-app/_babel_config_.js%22,%22cacheDirectory%22:%22/private/var/folders/1p/ymk34w294wb63nnmfb5ygk0c0000gn/T/embroider/webpack-babel-loader%22%7D!../../@embroider/webpack/src/virtual-loader.js?f=%252F%2540embroider%252Fext-cjs%252F%2540warp-drive%252Fcore-types%252Frequest&a=%252FUsers%252Fmattiaslyckne%252FCode%252Fglesys%252Fcloud%252Fclient:1
../../@embroider/babel-loader-9/index.js?{"variant":{"name":"dev","runtime":"browser","optimizeForProduction":false},"appBabelConfigPath":"/Users/mattiaslyckne/Code/glesys/cloud/client/node_modules/.embroider/rewritten-app/_babel_config_.js","cacheDirectory":"/private/var/folders/1p/ymk34w294wb63nnmfb5ygk0c0000gn/T/embroider/webpack-babel-loader"}!../../@embroider/webpack/src/virtual-loader.js?f=%2F%40embroider%2Fext-cjs%2F%40warp-drive%2Fcore-types%2Frequest&a=%2FUsers%2Fmattiaslyckne%2FCode%2Fglesys%2Fcloud%2Fclient! @ chunk.831ba69f90e4e0dcfcb6.js:407
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ cache-handler-XLbbNJdo.js:33
../rewritten-packages/@ember-data/store.56db784d/node_modules/@ember-data/store/cache-handler-XLbbNJdo.js @ chunk.514b3296aa8fe961418a.js:11590
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ -private.js:30
../rewritten-packages/@ember-data/store.56db784d/node_modules/@ember-data/store/-private.js @ chunk.514b3296aa8fe961418a.js:11579
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ -private.js:9
../rewritten-packages/@ember-data/graph.db8e8003/node_modules/@ember-data/graph/-private.js @ chunk.514b3296aa8fe961418a.js:11326
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ index.js:7
../rewritten-packages/@ember-data/json-api.39690375/node_modules/@ember-data/json-api/index.js @ chunk.514b3296aa8fe961418a.js:11337
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ store.js:5
../rewritten-packages/ember-data.00f088b0/node_modules/ember-data/store.js @ chunk.514b3296aa8fe961418a.js:14703
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ store.js:7
../rewritten-packages/ember-data.00f088b0/node_modules/ember-data/_app_/services/store.js @ chunk.514b3296aa8fe961418a.js:14648
__webpack_require__ @ chunk.3cfb315365df1011084b.js:31
eval @ glesys-controlpanel.js:52130
Module.exports @ loader.js:106
requireModule @ loader.js:27
get @ index.js:37
_extractDefaultExport @ index.js:388
resolveOther @ index.js:150
resolve @ index.js:171
resolve @ index.js:725
resolve @ index.js:506
resolve @ index.js:508
has @ index.js:738
has @ index.js:588
proto.validateInjections @ index.js:710
create @ index.js:369
create @ index.js:204
instantiateFactory @ index.js:276
lookup @ index.js:223
lookup @ index.js:121
lookup @ container_proxy.js:19
initialize @ bugsnag.js:153
(anonymous) @ index.js:142
Vertices.each @ dag-map.js:191
Vertices.walk @ dag-map.js:120
DAG.each @ dag-map.js:66
DAG.topsort @ dag-map.js:72
_runInitializer @ index.js:155
runInstanceInitializers @ index.js:140
_bootSync @ instance.js:86
didBecomeReady @ index.js:599
invoke @ backburner.js.js:272
flush @ backburner.js.js:188
flush @ backburner.js.js:344
_end @ backburner.js.js:773
end @ backburner.js.js:576
_run @ backburner.js.js:817
run @ backburner.js.js:611
run @ index.js:75
callback @ index.js:350
```

**Comment by happydude** [comment]
> Updated to 5.3.1 yesterday without any issues. But now when I'm updating to 5.3.2 I am getting this exact issue...
 Seeing the same, if I install 5.3.2 then nothing pulls in @warp-drive/core-types

**Comment by runspired** [comment]
5.3.3 on its way out the door, this will resolve it for the folks who hit this in 5.3.2, we may be stuck in a bit of confusion around why this happened to the folks in 5.3.1. Best I can tell those folks may be using packages separately from `ember-data`? If so, core-types is now a required peer-dep. If not, `ember-data` should be bringing it as a dependency and handling this for you, so if its still breaking we may need more help isolating why.

**Comment by runspired** [comment]
published https://github.com/emberjs/data/releases/tag/v5.3.3

**Comment by Jopie01** [comment]
I'm using the `5.4.0-alpha.22` version of Ember Data and using the separate packages:

```
"@ember-data/debug": "5.4.0-alpha.22",
"@ember-data/graph": "5.4.0-alpha.22",
"@ember-data/json-api": "5.4.0-alpha.22",
"@ember-data/request": "5.4.0-alpha.22",
"@ember-data/store": "5.4.0-alpha.22",
"@ember-data/tracking": "5.4.0-alpha.22",
```

So when this error popped up, I just installed the package and kept going.

**Comment by olyckne** [comment]
Tried 5.3.3 now and it seems to work fine 👏

**Comment by mkszepp** [comment]
@runspired confirm that it works without `ember-data` package, when we are adding `@warp-drive/core-types`.

While installing `@warp-drive/core-types` we get warning:
```
...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@warp-drive/core-types@0.0.0-alpha.3',
npm WARN EBADENGINE   required: { node: '>= 20.11.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@ember-data/private-build-infra@5.4.0-alpha.17',
npm WARN EBADENGINE   required: { node: '>= 20.11.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.1', npm: '10.2.4' }
npm WARN EBADENGINE }
...
```

**Comment by runspired** [comment]
@mkszepp yeah npm doesn't handle "latest" well for alpha/beta release when there is no stable 🙈. Might be something I can tweak in the publish script for alpha/beta release strategy packages though since it will technically always be a pre-release for them that should be latest

**Comment by runspired** [comment]
going to close since it seems bases are covered (for now)
